source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'NewsClient' do
    pod 'Alamofire', '~> 4.7'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'RxSwift', '~> 4.0'
    pod 'RIBs', '~> 0.9.1'
    pod 'SnapKit', '~> 4.0.0'
end
